const actionTypes = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_CLEAR_ERRORS: 'LOGIN_CLEAR_ERRORS'
}

export default actionTypes;