const types = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCTS_RECEIVED: 'GET_PRODUCTS_RECEIVED',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  GET_CATEGORIES: 'GET_CATEGORIES',
  LOADING: 'LOADING'
}

export default types;