const types = {
  FETCH_USERS: 'FETCH_USERS',
  LOGIN: 'LOGIN',
  LOGIN_CLEAR_ERRORS: 'LOGIN_CLEAR_ERRORS',
  LOGOUT: 'LOGOUT',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  REGISTER: 'REGISTER'
}

export default types;